### ISSUE TITLE
If I reboot my camera from the web gui it goes into limbo mode

### ISSUE THREAD

**Issue by Bram-diederik** [dbuezas/ha-addons#4]
My camera has some issues and looses connection after an hour or 6. 
It is still connected to the webgui (port 80) but no image is shown.
If i reboot the camera using the web gui it goes into limbo mode.

When turned on it only connects to the web gui for a brief time. then the connection to the web gui is lost. making the camera inaccessible. 

If i reboot the camera using the power button on the device. it reconnects with out any issue.

**Comment by dbuezas** [comment]
I'm afraid there's nothing I can do about this. These are just commands sent to the camera and I assume the one you have has a broken firmware. Maybe you can check if there is a firmware update in the original app
