### ISSUE TITLE
mosquitto version 2.0.18 running

### ISSUE THREAD

**Issue by VINCE-HA** [dbuezas/ha-addons#5]
Client ***MAC ADDRESS CAMERA*** disconnected, not authorised.
New connection from ***IP CAMERA***:37124 on port 1883.

**Comment by dbuezas** [comment]
These cameras need anonymous authentication mqtt brokers. Mosquito can't do that.
Take a look at the readme, there's a way to use without mqtt. Or use another broker specifically for this on a different ip
